site_name: Freelance CRM Docs
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          setup_commands:
            - import os
            - import sys
            - import django
            - sys.path.append(os.getcwd())
            - os.environ.setdefault("DJANGO_SETTINGS_MODULE", "crm.settings")
            - django.setup()
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true

nav:
  - Home: index.md
  - Telegram Bot: telegram_bot.md
  - Clients Module:
      - Validation Tests: clients/testing_clients.md
      - Clients: clients/clients.md
  - CRM Module:
      - Validation Tests: crm/testing_crm.md
      - CRM: crm/crm.md
  - Invoices Module:
      - Validation Tests: invoices/testing_invoices.md
      - Invoices: invoices/invoices.md
  - Projects Module:
      - Validation Tests: projects/testing_projects.md
      - Invoices: projects/projects.md