name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Prepare README for Hugging Face
        run: |
          # Create a title that needs a Hugging Face
          echo "---" > README_HF.md
          echo "title: My Multi Freelance Bot" >> README_HF.md
          echo "emoji: ðŸš€" >> README_HF.md
          echo "colorFrom: blue" >> README_HF.md
          echo "colorTo: indigo" >> README_HF.md
          echo "sdk: docker" >> README_HF.md
          echo "app_port: 7860" >> README_HF.md
          echo "pinned: false" >> README_HF.md
          echo "---" >> README_HF.md
          echo "" >> README_HF.md
          
          # Add the contents of regular README.md to the end
          cat README.md >> README_HF.md
          
          # Replace the old file with a new one only for deployment
          mv README_HF.md README.md

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add README.md
          git commit -m "Auto-inject HF metadata" --allow-empty
          git push --force https://Petakioto2:$HF_TOKEN@huggingface.co/spaces/Petakioto2/my-multi-freelance-bot main